# Generated by Django 4.1.1 on 2022-10-07 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('type', models.CharField(max_length=5)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='receipt.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField()),
                ('payment_method', models.CharField(max_length=30)),
                ('paid_price', models.FloatField()),
                ('tax_percentage', models.IntegerField()),
                ('gross', models.FloatField()),
                ('net', models.FloatField()),
                ('tax_price', models.FloatField()),
                ('receipt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='receipt.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=30)),
                ('terminal', models.CharField(max_length=30)),
                ('tse_transaktion', models.IntegerField()),
                ('tse_signatur_nr', models.IntegerField()),
                ('tse_start', models.DateTimeField()),
                ('tse_stop', models.DateTimeField()),
                ('tse_seriennummer', models.CharField(max_length=80)),
                ('tse_zeitformat', models.CharField(max_length=20)),
                ('tse_signatur', models.CharField(max_length=50)),
                ('tse_hashalgorithmus', models.CharField(max_length=20)),
                ('tse_status', models.CharField(max_length=20)),
                ('ust_id', models.CharField(max_length=30)),
                ('receipt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='receipt.receipt')),
            ],
        ),
    ]
