
version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
